### ISSUE TITLE
Add docs/cost-faq.md

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#12]

**Comment by galenriley** [comment]
Off the cuff costs:
- $99/yr for an Apple Developer account to publish to the App Store (unless someone in your SG is already a developer)
- $25 one-time registration fee to publish on Google Play (same as above)
- Base tier on heroku, ~$7/month. (That's not free, but way easier than standing up your own server... or if someone already has one and will let you add to it)

**Comment by galenriley** [comment]
this is information is already included in /docs/deployment.md

**Comment by tacoman** [comment]
I'm just going to update deployment.md to have an up-front "here's the cost" section so people can budget it out up-front before continuing.

**Comment by tacoman** [comment]
Added. Feel free to re-open if you think it needs more tweaks, but I think this is cleaner without splitting off a separate file.
