### ISSUE TITLE
Improve Drawer Hero background

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#134]
Drawer Menu hero image is now fixed height, 100% width, resizeMode: "cover"

Is there a way to make this look great across all screen sizes?

I just added Skin.NavigationDrawer_HeroOverlayHeightProportion to let the SGs configure how the overlay logo fits into this panel, but I feel like there's a better solution for the background image size than just fixed height.

**Comment by galenriley** [comment]
Maybe this whole thing should just be a single image, rendered just like we want it to look, and we should abandon this background/transluscency/logo sandwich idea. That doesn't correct the fixed height / UI prettiness issue, but it removes a convoluted layout and configuration

**Comment by galenriley** [comment]
/components/HomeVideoPanel and VideoBackground are just as wonky, with the added difficulty that we don't know the proportions of the video file itself

**Comment by galenriley** [comment]
Added Skin.NavigationDrawer_HeroBackgroundHeight, so at least the fixed height is configurable

**Comment by tacoman** [comment]
Is the above considered an acceptable solution?

**Comment by galenriley** [comment]
Suboptimal, but acceptable. Closing.
