### ISSUE TITLE
Use in-app browser to open web links

### ISSUE THREAD

**Issue by wedemmoez** [Chattahooligans/hooligan-hymnal-app#137]
In 2.0.0, the app link behavior was changed to open links to external sites in the OS browser. The user then has to manually switch back to the application.

**Comment by galenriley** [comment]
Will do this inside config, but should name the config property with the assumption that this behavior will eventually be a user setting

**Comment by galenriley** [comment]
Maybe the config should have two flags, one for each platform?

**Comment by wedemmoez** [comment]
For now that might be a fine solution. I really like the idea of making it a user choice in the future

**Comment by galenriley** [comment]
Proposed implementation in #141 for v2.1.0. Please review.

**Comment by galenriley** [comment]
@wedemmoez , so this makes sense for links baked into the app, like in the drawer menu

Does it make sense for links in the text of news feed posts?

**Comment by wedemmoez** [comment]
Links in text posts can be linked to the config option? it should be a global setting

**Comment by galenriley** [comment]
It's currently a single global setting, just didn't know if posts in the news feed should be different

**Comment by galenriley** [comment]
@wedemmoez, I know link handling came up again today in conversation. Can you either make a request for me or close this issue ticket?

**Comment by wedemmoez** [comment]
Not urgent, but possibly a way to select which links open in an internal browser vs externally? its an extremely limited use case so I'm going to close this until it becomes a necessity.
