### ISSUE TITLE
Add docs/assets

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#15]
Some documentation about what a SG should gather to customize the app: common RGB colors, images & resolutions, preferred fonts, etc

**Comment by tacoman** [comment]
Did you grab your palette by using the exact RGB values of your crest? That's what we did to get the rouge for Guardbook.

I'll try to get to this one soon. Having to figure out what combo of transparencies, resolutions, etc. was a pain. I'll link to it from deployment.md as well.

**Comment by galenriley** [comment]
Yes, eyedropper tool.

It would be a service, but far from required to figure out the resolution stuff. Honestly, it's a mishmash, some of it doesn't matter, and everything is subject to change in the UI. 

I recall being annoyed at needing a 512px square icon for Google Play and a 1024px square one for App Store. I had some 1000x1000 images that we'd been using for social media stuff all year and those wouldn't work for either. In a perfect world, the developer can hand such a reference off to a design person and they can just run the whole checklist and deliver everything at once. (My assets aren't clean or organized; that's been on my to-do list for a while)

**Comment by tacoman** [comment]
Added this and added a link to it in deployment.md.
