### ISSUE TITLE
Admin / copy roster

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#157]
In theory, clubs can expect some commonality from season to season. To save on data entry time, add the ability to make a copy of an existing roster. Prompt for a new roster title (and other fields that must change, as appropriate), and copy the players list to the new db record.

Is this a good idea and can it be implemented before NISA 2021 Spring season player signings?

**Comment by cMoney667** [comment]
I will look into this either tonight or tomorrow

**Comment by tacoman** [comment]
PR was merged and feature is in use.
