### ISSUE TITLE
Create BigButton component

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#17]
make sure it supports RTL layout

**Comment by tacoman** [comment]
What's this for again?

**Comment by galenriley** [comment]
We use this nested ClipBorderRadius/RectButton component all over and there's a lot of copy paste code. It's just an opportunity to clean up in the future

However
- the send/send+notify buttons are different than the rest
- the foes buttons are different than the rest and may become more different once we figure out an elegant way to use the secondary color property
