### ISSUE TITLE
Foes: Import CSV

### ISSUE THREAD

**Issue by tacoman** [Chattahooligans/hooligan-hymnal-app#178]
If the foes list could take in a CSV, it would greatly speed up data entry. In particular, some of our team is fluent with Excel macros and may be able to automatically scrape the UWS site and transform it into a spreadsheet.

**Comment by Hucxley** [comment]
PapaParse is great for this, but I'm not sure if this is a client-side or server-side need.  Maybe on client-side, just need standard file input with a reader, and pass the blob to PapaParse to convert server-side.  Then again, if the server is already configured to take a JSON payload, just convert it on the client when the file is uploaded and send the JSON payload like normal.  Here's the link to PapaParse for React (edit: more specific docs based on the request):
https://react-papaparse.js.org/#local-files

I've used it for some of my Vue projects, and it works great.

**Comment by tacoman** [comment]
Is React required?

**Comment by Hucxley** [comment]
That's what the rest of the app is written in, so, unless there's a different place that people would be uploading roster files to, I'd assume so.  It's basically just adding a component to upload a file, and then converting what's uploaded to what the server is expecting (again, I assume a JSON payload).

**Comment by tacoman** [comment]
The app is written in React Native (separate from real React to my understanding), but the admin tools for editing roster data are a non-React website.

**Comment by Hucxley** [comment]
> The app is written in React Native (separate from real React to my understanding), but the admin tools for editing roster data are a non-React website.

I don't know where that admin site is, but as long as it's not Word Press or something, PapaParse in plain JS is easy enough.  I may not have that repo on my watch list since I'm new here.

**Comment by galenriley** [comment]
https://github.com/Chattahooligans/hooligan-hymnal-server

**Comment by tacoman** [comment]
The PR in the server has been merged.
