### ISSUE TITLE
Error posting with picture

### ISSUE THREAD

**Issue by Mbwata** [Chattahooligans/hooligan-hymnal-app#188]
![IMG_1832](https://user-images.githubusercontent.com/44037139/140663464-d0f042d6-f6a4-45f3-875a-9b0a2c4723ac.PNG)

When submitting a post with an image in it, I get an error and the post doesn't go through.

**Comment by galenriley** [comment]
What are you seeing in your server/heroku logs when this happens? Hopefully
there's a good clue on that end.

**Comment by Mbwata** [comment]
This is all I saw when I looked at the logs:

::ffff:10.42.0.252 - - [07/Nov/2021:22:29:14 +0000] "POST /api/feed HTTP/1.1" 500 - "-" "Expo/2.21.3.1012198 CFNetwork/1312 Darwin/21.0.0"

Posts without pictures seem to work just fine

**Comment by galenriley** [comment]
@shortnd - you are the

**Comment by galenriley** [comment]
@Mbwata - Have you uploaded images successfully before? It's possible that cloudinary never got set up/connected/configured.

@shortnd - You're our server-side expert, here. Do you have any ideas?

**Comment by Mbwata** [comment]
I've never been able to do it.
I'm also running on a year old version of the server code. Not sure if there is anything in a newer version that might fix it. I've been playing with this off and on for like a year and we're wanting to get it up and running before we start in MLS. I barely know what I'm doing here but "knows enough to be dangerous" makes me the most qualified in our SG.

**Comment by galenriley** [comment]
I would recommend reviewing the Hooligan Hymnal setup docs for the
Cloudinary bits and making sure you are registered and have API keys and
whatnot first. Getting on the current branch of the server code is probably
a safe bet, and ensuring all of the environment variables are correct.

**Comment by Mbwata** [comment]
Guys I totally missed the Cloudinary setup. That sounds like that's my issue.
