### ISSUE TITLE
accomodate filtering on .active property in players/rosters/songs/etc

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#20]

**Comment by tacoman** [comment]
Rosters already filters on an /active endpoint, we can replicate the same pattern for the others

**Comment by galenriley** [comment]
Active isn't a clear concept for me in all of these data types.

**Comment by tacoman** [comment]
Rosters: Active rosters are currently competing/competing this year. E.g. Members Cup squads will cease to be "active" when 2020 signings are announced. In the past, you might have simply backed up the data and deleted it from production. By marking it inactive instead, you can keep the data around for API consumers or for a future feature that shows historical data.

Songs: Inactive songs might be chants that are retired, or just aren't relevant and thus shouldn't be in the interface. 

In practice, you probably would handle this by simply not referring to songs in the songbooks object. Similarly, a player doesn't necessarily have to be inactive, just not referred to in a roster. From that perspective, this issue might actually be done and ready to be closed.

**Comment by galenriley** [comment]
Those make total sense. I was struggling to wrap my brain around active for players and news feed items.

For players, only make them inactive if you wanna keep them in the database but hide them from the UI. Like if a player got arrested for something awful and you wanted to pull them..

For news feed, it's a way to remove an item (that is seperate from the unpublish timestamp...which won't be used all that often)

okay yeah i got it now. Let's keep the issue open until the flags are implemented across the main data types?

**Comment by tacoman** [comment]
Players can still just have their entry removed from the roster object if you wanted to hide them. The only way I see an active flag being needed for something like that is if you did something like build a web interface that could search all players across all years and you wanted a player's data but not to make it available for some reason. I'd rather just edit the bio with a note and be up-front about the shame, but I suppose some other groups might keep hidden archives.

If we're in agreement on that, then it only leaves news feed. I still think the best way to deal with that is to just delete the data if it's no longer desired.
