### ISSUE TITLE
Post-i18n fixes

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#3]
For About screen:
- use <ParsedText/> controls everywhere
- change Credits section to an array and build dynamically

For Home screen:
- accommodate burger menu icon somehow

**Comment by galenriley** [comment]
On the latter, probably break the item to into substrings around something like %ICON% and build dynamically? Just a note to self for later

**Comment by galenriley** [comment]
Did the ParsedText thing and the dynamic credits thing, did NOT handle the icon thing yet,thus the ticket is still open

**Comment by tacoman** [comment]
Outstanding rtl bugs:

- ✔️ songbook TOC: chapter headings are not aligning to the right
- roster: inverting the Foes/Friends tab order causes Foes to be selected first. (Might need to trigger it with code when the component mounts)
- RosterFoesPlayers: should we flip the back button's orientation and positioning?
- Player: bio is not right-aligning. Might be an error in the ParsedText library
- Capo screens: have not been verified yet
- Nav drawer: Is not respecting alignment when testing with English (might work when rtl strings are input)

**Comment by galenriley** [comment]
Handled the icon thing ✅

**Comment by galenriley** [comment]
Player bio is wrapped in a `<ReadMore>` component. If `<ParsedText>` works without issue in the other scenarios where it's used, then the issue is in `<ReadMore>` and maybe there's a property to set alignment in it

Edit:
I think this module is `expo/react-native-read-more-text` and it doesn't inherit the parent props like our own `<StyledText>` does

**Comment by galenriley** [comment]
Songbook ToC uses a `<SectionList>` component. I know you can override how the section headers render, but we're just using default stuff

Trivia: the multi-roster page used to have the exact same implementation. But we don't use SectionList there anymore

Future issues:
We DO use the same SectionList on the GK nickname page for selecting a color, so the TOC fix will probably apply there as well

**Comment by galenriley** [comment]
The issue described in the initial comment is resolved. Close this and create a new issue just for RTL, @tacoman ?

Good news is GitHub Issues support checklists now, which is very handy

**Comment by galenriley** [comment]
@tacoman, I'm closing this Issue. Please consider a fresh ticket when we wanna give RTL another look.
