### ISSUE TITLE
Admin /players/ changes

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#32]

**Comment by galenriley** [comment]
For the player list:
- sort by alpha on .name
- restrict size of thumbnail image
- put everything in a container that is clickable to go to the View player form (or make the thumbnail a link, as a backup plan)
- add squadNumber to the container (right of player name?)
- add "View" and "Edit" links to the container That go to the respective form for the player

**Comment by galenriley** [comment]
if no player thumbnail, render a circle (in whatever the default UI color is. it's whatever) so everything stays aligned

**Comment by galenriley** [comment]
add a field at the very bottom that's something like "{n} Players in database" where {n} is a count of records

**Comment by galenriley** [comment]
server: change server to save thumbnails at 200x200 instead of 50x50

server/admin, both: change .image to be .images: [] and set the first array item to the image that already exists
(I know you JUST did something similar for player biographies)

**Comment by galenriley** [comment]
add .position to the container

**Comment by cMoney667** [comment]
Closing issue as https://github.com/Chattahooligans/hooligan-hymnal-server/commit/fcc6320930031487d739b3ccfb202ba2c6b7828f Fixed these issues
