### ISSUE TITLE
UIWebView deprecated by Apple

### ISSUE THREAD

**Issue by tacoman** [Chattahooligans/hooligan-hymnal-app#33]
Apple will stop accepting builds that use the UIWebView API eventually. We need to figure out which package is pulling it in- Apple won't be scanning our JS, so it's something that's included in a native module.

I've seen indications that this might be related to React Native < 0.60; Expo SDK 35 runs on 0.59.8. So it's possible that all we need to do is wait for Expo SDK 36 and upgrade; we'll need to prioritize doing so when it launches. If not, this issue will be used to keep track of additional research.

**Comment by galenriley** [comment]
I cannot find it now, but I recall researching this issue and ending up on some post in the Expo forums that said it was a dependency they were using and they would have it fixed in SDK before Apple started denying those builds

**Comment by galenriley** [comment]
will be fixed in expo SDK 37, but we must submit new builds before apple stops accepting them in April 2020

**Comment by galenriley** [comment]
Fixed in 2.0. (Assuming expo ain't lyin about SDK37)
