### ISSUE TITLE
Organize and rename assets, reflect changes in assets.md

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#34]

**Comment by galenriley** [comment]
The third SG that comes online could take this task, do the research and cite the various store guidelines.

**Comment by wedemmoez** [comment]
I can work on this! Swapping assets to DBG now, I'll make notes of where everything is referenced

**Comment by galenriley** [comment]
suckerrrr

**Comment by galenriley** [comment]
(Thank you!! The endgame is to have assets.md address everything a new SG might want to know so they can prep their stuff.)

**Comment by galenriley** [comment]
@wedemmoez , I'm working this in the two-dot-oh branch right now

**Comment by galenriley** [comment]
Done, son!
