### ISSUE TITLE
serverConfig and sharedConfig (and appConfig) documents on the server

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#36]
with APIs to get sharedConfig (and appConfig, future use)

**Comment by galenriley** [comment]
```
sharedConfig = 
{
  inputLanguages: ['en', 'es']
}
```

key name negotiable, but this setting will be used to let content creators select the language they are inputting news feed items in. Because this feature will eventually be used on the admin as well (keyboards > thumbs), it belongs in sharedConfig

**Comment by tacoman** [comment]
We will need to ensure that we save the sharedConfig locally in global storage and default to the saved version when loading in offline mode.

**Comment by tacoman** [comment]
Closing. The config is inherently tied to the client code, not the current state of the server. YAGNI > DRY in this case.
