### ISSUE TITLE
Player birthdays: feed posts/push notifications

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#37]

**Comment by tacoman** [comment]
This will require some logic around our new scheduled posts functionality. Anytime we save a player, we should check for the birthday changing. If so, run a search in scheduledtasks for any items that have a matching .playerId and type="birthday reminder", and clear them out. (We need to do this for both the in-memory scheduler and in Mongo.) Regardless, add a new task that publishes a templated news feed item to a channel "player birthdays", with the appropriate attachment.

**Comment by tacoman** [comment]
Just noting that this is likely not going to be of interest for the NGS devs since we'd be absolutely flooded. I think an acceptable workaround would be to use scheduled posts once finished to set these up manually if desired. Can we close it?

**Comment by galenriley** [comment]
Yeah, happy to close this one for now. Clubs are starting to pick up this task anyway.
