### ISSUE TITLE
Change /api/controller/active endpoints to /api/controller/all

### ISSUE THREAD

**Issue by tacoman** [Chattahooligans/hooligan-hymnal-app#45]
By default Hooligan Hymnal is currently only pulling active data. The default endpoint should reflect that; if someone is using the API to retrieve historical data, they'll append /all rather than omitting /active.

**Comment by galenriley** [comment]
Think we can get this in as part of that big 2.0 release, @tacoman ?

**Comment by tacoman** [comment]
Addressed as part of https://github.com/Chattahooligans/hooligan-hymnal-app/pull/112 and https://github.com/Chattahooligans/hooligan-hymnal-server/pull/72

**Comment by galenriley** [comment]
/api/foes got skipped. Can you check the others, just to be sure, @tacoman?
