### ISSUE TITLE
Admin players/{id} changes

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#46]
SERVER
- change server to save thumbnails at 200x200 instead of 50x50
- remove .team from schema
- change .image to be .images: [] and set the first array item to the image that already exists
(I know you JUST did something similar for player biographies)

ADMIN
Show .thumbnail at top of this screen
Remove .team field (after change, above)
Display bios in tabs (similar to edit screen)
Edit/Delete links as buttons
General styling improvements

**Comment by galenriley** [comment]
Add .active field to player and admin UI
Remove delete functionality

(Someone on our side accidentally deleted the captain...oops)

**Comment by cMoney667** [comment]
Merged in changes to master
