### ISSUE TITLE
decide on npm/yarn, tidy up package lock, write package manager guide

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#49]

**Comment by galenriley** [comment]
PS C:\Users\galen\Chattahooligans\hooligan-hymnal-app> expo start
Starting project at C:\Users\galen\Chattahooligans\hooligan-hymnal-app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-gesture-handler - expected version range: ~1.3.0 - actual version installed: ^1.4.1
 - react-native-reanimated - expected version range: ~1.2.0 - actual version installed: ^1.3.0
 - react-native-screens - expected version range: ~1.0.0-alpha.23 - actual version installed: ^2.0.0-alpha.4
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
Starting Metro Bundler on port 19001.

**Comment by tacoman** [comment]
NPM. Apparently its advanced by quite a bit and it's what I've been reaching for by default and having the most luck with.

**Comment by tacoman** [comment]
Hit merge on the two linked PRs and we're golden.

**Comment by tacoman** [comment]
@galenriley I know we ran into some kind of issue with this, why did we need to re-open?

**Comment by galenriley** [comment]
No recollection

**Comment by tacoman** [comment]
I'm going to close this for now then. If there's an outstanding issue, we can re-open.
