### ISSUE TITLE
Add dynamic items to the container that holds nav drawer that launch outside links/internal UIWebBrowser

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#5]

**Comment by galenriley** [comment]
This stuff lives in <CustomDrawer/> and we haven't actually looked at that code since the very first release. Probably lots of room for tweaks

**Comment by tacoman** [comment]
Having collapsible groups as part of this would be nice.

Standings
-NISA
-UWS

etc

**Comment by galenriley** [comment]
configurable web links in the drawer are part of nav5 refactor

Collapsible groups aren't supported yet, and idk how to implement such a thing right now, so that's up to @tacoman to keep this Issue open or nah
