### ISSUE TITLE
Admin /songs/ changes

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#54]
Mirror /players/ with styled title, styled "Create Song" button, panels around each title, filter search box (and pagination if you want to be consistent with the Players index screen)

**Comment by galenriley** [comment]
Have filter include fields:
title, lyrics, reference title, category

**Comment by galenriley** [comment]
Most of this is done. Is it possible to include those extra fields in the same search on the filter box? 
I do something very similar here (but I forgot category)
https://github.com/Chattahooligans/hooligan-hymnal-app/blob/master/src/screens/PostAttachmentSelectSong.js

**Comment by cMoney667** [comment]
They should already be in there..

**Comment by galenriley** [comment]
.title, .lyrics work

.referenceTitle, .category do not

**Comment by galenriley** [comment]
changing reference_title to referenceTitle in the logic, which may fix the first part. No idea why .category isn't searching

**Comment by galenriley** [comment]
that fixed it for .referenceTitle, nothing for .category though

I don't have enough understanding to troubleshoot why

**Comment by cMoney667** [comment]
Ok will look at in the morning and get it fixed
