### ISSUE TITLE
Admin /songs/{id} changes

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#55]

**Comment by galenriley** [comment]
Styling all over

**Comment by galenriley** [comment]
Remove unused fields:
- delete_local

Rename fields to: (in an effort to fix fucked up naming conventions)
- referenceTitle
- referenceLink
- playerId

**Comment by galenriley** [comment]
Arrange (subset of) fields in order, similar to order in the app

- Title
- Reference Title
- Instructions
- Lyrics

- Reference Link
- Sheet Music Link
- Player (lookup in Players collection, show...uhhh...card similar to Players index...thumbnail/name/number/position)

**Comment by galenriley** [comment]
For songs/{id}/edit

(flexible on this)
Some UI to map a player to the song's .playerId field
Maybe a filter box to search? Maybe a dropdown with names? 

Note that we may need to take a song that has a player and set the field to null, so accomodate that scenario

**Comment by galenriley** [comment]
This is pretty great. The only change that I'd like is to alpha-sort the player dropdown

**Comment by cMoney667** [comment]
Closing issue as it was addressed on Feb 2nd
