### ISSUE TITLE
Add Partners screen in drawer

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#59]
SGs may want to promote other initiatives that aren't strictly part of the SG operations- podcasts, bars, charities, etc

Accommodate this in the app

**Comment by galenriley** [comment]
Bonus idea- take the cards on this screen an randomly select or splice one into the feed

**Comment by tacoman** [comment]
There is now a "Fan projects (unaffiliated)" option that resides with the official social medias in the news feed.
