### ISSUE TITLE
Add example_Settings.js (config), example_app.json, and other related files to facilitate new deployments

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#67]

**Comment by tacoman** [comment]
What would be even more powerful: default_settings.js, default_app.json. And then have the overrides be in a separate file, and the app merges them together into one object at runtime.

That way if something is changed like font sizes, colors. etc. in the defaults or in the Chattahooligan version, I can cleanly merge without fear of having my current settings overridden.

**Comment by tacoman** [comment]
See also https://github.com/Chattahooligans/hooligan-hymnal-app/issues/36 when working on this. It probably makes sense to tackle both of these at once since they involve significant configuration reworks.

**Comment by galenriley** [comment]
config-example.js will exist in 2.0

I like the idea of merging stuff on top of defaults, but that pattern falls apart for app.json and the locale file. Still wanna investigate that or safe to close the issue?
