### ISSUE TITLE
Standardize server data structure naming conventions

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#7]
Some are camel case, others have underscores. It's a mess

**Comment by galenriley** [comment]
re: naming conventions, here's part of it-

https://mongoosejs.com/docs/models.html#compiling

**Comment by tacoman** [comment]
Looks like camelCase is the preferred option by both myself and the docs. Renaming can be done via: https://docs.mongodb.com/manual/reference/operator/update/rename/

So this will require updating the field name references in the schema and the client code, and then creating a script full of these rename statements to fix.

@galenriley  and @wedemmoez , please set yourself as watchers on this issue so you can perform the update when the time comes; we're all going to have to run the script manually. PLEASE BACKUP YOUR DATABASES FIRST.
